version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      # Admin console
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      # Sólo el JSON de tu realm, en modo lectura
      - ./realm-export.json:/opt/keycloak/data/import/realm.json:ro