# 1) Indica versión de Mongo embebido (Flapdoodle)
spring.mongodb.embedded.version=6.0.13

# 2) Anula la URI de Atlas y apunta a localhost (embebido)
spring.data.mongodb.uri=mongodb://localhost:27017/empoderat_db

# Opcionalmente (no estrictamente necesario si defines uri):
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=empoderat_db

# 3) Crea índices automáticamente en el embebido
spring.data.mongodb.auto-index-creation=true

# 4) Cualquier otra configuración de logging en dev:
logging.level.org.springframework.data.mongodb=DEBUG
